<?php if ($block->getData('title')) : ?>
  <div class="hb-wrapper below-padding" style="background: #ffffff;">
    <div class="page-title-main">
      <!-- <strong><?php echo $block->getData('title'); ?> </strong> -->
    </div>
    <div class="block-content">
      <?php
      $er_url = "https://portal.vietcombank.com.vn/Usercontrols/TVPortal.TyGia/pXML.aspx?b=68";
      $ch = curl_init();
      curl_setopt($ch, CURLOPT_URL, $er_url);
      curl_setopt($ch, CURLOPT_FAILONERROR, 1);
      curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
      curl_setopt($ch, CURLOPT_TIMEOUT, 15);
      curl_setopt($ch, CURLOPT_VERBOSE, true);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
      curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
      $res = curl_exec($ch);
      curl_close($ch);
      $xml = simplexml_load_string($res);
      $json = json_encode($xml);
      $rs = json_decode($json, TRUE);
      echo '<table style="width: 100%; font-size:15px" id="currency" class="table table-hover table-bordered table-striped">';
      echo  "<thead class='thead-dark'><tr class='table-bordered'>
      <th scope='col'>Currency Code</th>
      <th scope='col'>Curency Name</th>
      <th scope='col'>Unit</th>
      <th scope='col'>Buy Price(VND)</th>
      <th scope='col'>Sell Price(VND</th>
      <th scope='col'>Transfer Price(VND)</th>
      </tr></thead>";
      ?>
      <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" crossorigin="anonymous">
      <?php echo "<tbody class='table-hover>'"; ?>
      <?php
      foreach ($rs["Exrate"] as $r) {
        $r = $r["@attributes"];
        echo "<tr>";
        echo "<td>";
        echo $r["CurrencyCode"];
        echo "</td>";
        echo "<td>";
        echo $r["CurrencyName"];
        echo "</td>";
        echo "<td>";
        echo "1 ".$r["CurrencyCode"];
        echo "</td>";
        echo "<td>";
        echo $r["Buy"];
        echo "</td>";
        echo "<td>";
        echo $r["Sell"];
        echo "</td>";
        echo "<td>";
        echo $r["Transfer"];
        echo "</td>";
        echo "</tr>";
      }
      echo "</tbody></table>";
      ?>
    </div>
  <?php endif; ?>